apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee
  ports:
    - protocol: TCP
      port: 3009
      targetPort: 3009
    - protocol: TCP
      port: 3010
      targetPort: 3010
