version: '3.8'
services:

  resume-view:
    build:
      context: .
      dockerfile: resume-view/Dockerfile

    env_file:
      - resume-view/.env

    image: resume-view:latest

    ports:
      - "3007:3007"
      - "3030:3030"

    depends_on:
      - postgres
      - jaeger
      - kafka

    environment:
      WAIT_HOSTS: postgres:5432, jaeger:4317, kafka:9092, prometheus:9090
      WAIT_BEFORE: 5

    networks:
      - backend-network

  echo-service:
    build:
      context: .
      dockerfile: echo-service/Dockerfile

    environment:
      - "VIEW_SERVICE_ENDPOINT=resume-view:3007"
      - "CLIENT_TIMEOUT=5s"
      - "RETRIES_COUNT=3"
      - "SERVER_PORT:3008"
      - "LOG_LEVEL=DEBUG"

    image: echo-service:latest

    ports:
      - "3008:3008"

    depends_on:
      - resume-view

    networks:
      - backend-network

  employee-service:
    build:
      context: .
      dockerfile: employee-service/Dockerfile

    image: employee-service:latest

    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=vercello"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_DB=resume-views"
      - "POSTGRES_SSL_MODE=disable"

      - "MONGO_HOST=mongo"
      - "MONGO_PORT=27017"
      - "MONGO_DB=employees"
      - "MONGO_REPLICA_SET=rs0"

      - "KAFKA_HOST=kafka"
      - "KAFKA_PORT=9092"
      - "KAFKA_TOPIC=employees-events"

      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

      - "MAIN_DATABASE=postgres"
      - "LOG_LEVEL=INFO"
      - "SERVER_PORT=:3009"
      - "WAIT_HOSTS=postgres:5432,mongo:27017,kafka:9092"
      - "WAIT_BEFORE=5"

    ports:
      - "3009:3009"

    depends_on:
      - postgres
      - mongo

    networks:
      - backend-network

  postgres:
    container_name: resume-view_postgres
    image: postgres:latest

    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=vercello"
      - "POSTGRES_DB=resume-views"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

    healthcheck:
      test: pg_isready -U postgres -d resume-views
      interval: 10s
      timeout: 3s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - backend-network
    command: [ "-path", "migrations", "-database",  "postgres://postgres:vercello@postgres:5432/resume-views?sslmode=disable", "up" ]
    depends_on:
      - postgres
    volumes:
      - migrations:/migrations

  mongo:
    image: mongo:latest
    container_name: resume-view_mongodb
    environment:
      MONGO_APP_DATABASE: employees
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27018
    entrypoint: >
      /bin/bash -c '
      echo "rs.initiate()" > /docker-entrypoint-initdb.d/1-init-replicaset.js &&
      /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --noauth' "'MONGO_APP_DATABASE'" "'init'" "'db initialized successfully'"
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: resume-view_redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - backend-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - backend-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    networks:
      - backend-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "employees-events:3:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - backend-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - backend-network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:9092'
    networks:
      - backend-network


volumes:
  pgdata:
  mongo_data:
  mongo_config:
  redis:
  migrations:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'migrations'

networks:
  backend-network:
    driver: bridge