version: '3.8'
services:

  resume-view:
    build:
      context: resume-view
      dockerfile: Dockerfile

    env_file:
      - resume-view/.env

    image: resume-view:latest

    ports:
      - "3007:3007"

    depends_on:
      - postgres
      - jaeger

    environment:
      WAIT_HOSTS: postgres:5432, jaeger:4317

    networks:
      - backend-network

  echo-service:
    build:
      context: echo-service
      dockerfile: Dockerfile

    environment:
      - "VIEW_SERVICE_ENDPOINT=resume-view:3007"
      - "CLIENT_TIMEOUT=5s"
      - "RETRIES_COUNT=3"
      - "SERVER_PORT:3008"

    image: echo-service:latest

    ports:
      - "3008:3008"

    depends_on:
      - resume-view

    networks:
      - backend-network

  postgres:
    container_name: resume-view_postgres
    image: postgres:latest

    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=vercello"
      - "POSTGRES_DB=resume-views"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network


  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge