{
 "title": "mydashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Resume Views",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (resume_id) (resume_views_total)"
    }
   ]
  },
  {
   "title": "Total Resume Views Gauge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resume_views_total_gauge" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode!=\"idle\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} * 100"
    }
   ]
  }
 ]
}