env: "local"
client_timeout: "5s"
retries_count: "5"

server:
  port: "3008"

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  name: "views"
  password: "password"
  ssl_mode: "disable"

jaeger:
  endpoint: "localhost:4317"

clients:
  application_service_url: "localhost:3006"