apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: edpg5l3bp883ka
    isDefault: true
    jsonData:
      timeInterval: "5s"
