// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Verce11o/resume-view/employee-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	models "github.com/Verce11o/resume-view/employee-service/internal/models"

	uuid "github.com/google/uuid"
)

// PositionRepository is an autogenerated mock type for the PositionRepository type
type PositionRepository struct {
	mock.Mock
}

// CreatePosition provides a mock function with given fields: ctx, req
func (_m *PositionRepository) CreatePosition(ctx context.Context, req domain.CreatePosition) (models.Position, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreatePosition")
	}

	var r0 models.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePosition) (models.Position, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePosition) models.Position); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.Position)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreatePosition) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePosition provides a mock function with given fields: ctx, id
func (_m *PositionRepository) DeletePosition(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePosition")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPosition provides a mock function with given fields: ctx, id
func (_m *PositionRepository) GetPosition(ctx context.Context, id uuid.UUID) (models.Position, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPosition")
	}

	var r0 models.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Position, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Position); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Position)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPositionList provides a mock function with given fields: ctx, cursor
func (_m *PositionRepository) GetPositionList(ctx context.Context, cursor string) (models.PositionList, error) {
	ret := _m.Called(ctx, cursor)

	if len(ret) == 0 {
		panic("no return value specified for GetPositionList")
	}

	var r0 models.PositionList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.PositionList, error)); ok {
		return rf(ctx, cursor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.PositionList); ok {
		r0 = rf(ctx, cursor)
	} else {
		r0 = ret.Get(0).(models.PositionList)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cursor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePosition provides a mock function with given fields: ctx, req
func (_m *PositionRepository) UpdatePosition(ctx context.Context, req domain.UpdatePosition) (models.Position, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 models.Position
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdatePosition) (models.Position, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdatePosition) models.Position); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(models.Position)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdatePosition) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPositionRepository creates a new instance of PositionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPositionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PositionRepository {
	mock := &PositionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
