name: TestCode
run-name: Testing code
on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Tests
        run: make test

      - name: Run Lint
        run: make lint

      - name: Run Build
        run: make build
