name: TestCode
run-name: Testing code
on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: make test

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5.0.0

      - name: Run Build
        run: make build
