name: Build project
run-name: Building project

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
    branches:
      - 'main'


jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.1'
          cache-dependency-path: go.sum

      - name: Run Build
        run: make build
